// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA-qac8F7CqQEqwmbfpipKT_mxkuhJRA8',
    appId: '1:539946444022:web:8040cb716d007532eff8d7',
    messagingSenderId: '539946444022',
    projectId: 'totalx-work',
    authDomain: 'totalx-work.firebaseapp.com',
    storageBucket: 'totalx-work.appspot.com',
    measurementId: 'G-2ZYV5FRBGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5Y-FVla5wKWhhUGbSfrZl1zApMi1FGeA',
    appId: '1:539946444022:android:71f9f292ffb4f194eff8d7',
    messagingSenderId: '539946444022',
    projectId: 'totalx-work',
    storageBucket: 'totalx-work.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEX-e_-XhH8zz9CdYMY4lKQHjP8lgsw24',
    appId: '1:539946444022:ios:26fe188736595429eff8d7',
    messagingSenderId: '539946444022',
    projectId: 'totalx-work',
    storageBucket: 'totalx-work.appspot.com',
    iosClientId:
        '539946444022-96g8f9bi9bol6kq1k5nttiekab11df1a.apps.googleusercontent.com',
    iosBundleId: 'com.example.totalXWork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEX-e_-XhH8zz9CdYMY4lKQHjP8lgsw24',
    appId: '1:539946444022:ios:7239c3afbcf462d0eff8d7',
    messagingSenderId: '539946444022',
    projectId: 'totalx-work',
    storageBucket: 'totalx-work.appspot.com',
    iosClientId:
        '539946444022-u864pg68119bbrgg7f96aq2jgdmfpmdb.apps.googleusercontent.com',
    iosBundleId: 'com.example.totalXWork.RunnerTests',
  );
}
